[setup.backends."v4"]
description = "v4"
address = "hiimslimshady.edu"
port = 443

[setup.config_stores."weather_auth".items.key]
description = "API token for openweathermap.org"
input_type = "string"
